# -*- coding: utf-8 -*-
"""pipeline_seg_UNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6BZBRJEZ3cq-XIgztmbZs7aPVLQpQh_
"""

import tensorflow as tf
from tensorflow import keras
from keras.utils import normalize
from keras.metrics import MeanIoU
import os
import cv2
import numpy as np
from matplotlib import pyplot as plt
from keras.optimizers import Adam
import glob
from google.colab import drive
drive.mount('/content/drive')

# image_directory ='/content/drive/MyDrive/bolt_data_new/corres_images_rename/'
# mask_directory = '/content/drive/MyDrive/bolt_data_new/PixelLabelData_rename/'


# image_names = glob.glob('/content/drive/MyDrive/bolt_data_new/corres_images_rename/*.jpg')
# image_names.sort()
# mask_name = glob.glob('/content/drive/MyDrive/bolt_data_new/PixelLabelData_rename/*.png')
# mask_name.sort()

# print(len(mask_name), len(image_names))







from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test = train_test_split(img_dataset,mask_dataset,test_size=0.20,random_state=12)

# import albumentations as A
# l = []
# for i, j in zip(image_names, mask_name):
#   img = cv2.imread(i)[:,:,::-1]
#   l.append(img)

#   mask = cv2.imread(j,0)
#   l.append(mask)

#   transform = A.RandomBrightnessContrast(brightness_limit=(0.1, 0.3), contrast_limit=(0.1, 0.3), p=1.0, always_apply=True)
#   RBC = transform(image=img, mask=mask)
#   cv2.imwrite(i.split('.')[0]+'_RBC.'+i.split('.')[1], RBC['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_RBC.'+j.split('.')[1], RBC['mask'])


#   transform = A.HorizontalFlip(p=1.0, always_apply=True)
#   HFlip = transform(image=img, mask=mask)
#   cv2.imwrite(i.split('.')[0]+'_HFlip.'+i.split('.')[1], HFlip['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_HFlip.'+j.split('.')[1], HFlip['mask'])

#   transform = A.VerticalFlip(p=1.0, always_apply=True)
#   VFlip = transform(image=img, mask=mask)
#   cv2.imwrite(i.split('.')[0]+'_VFlip.'+i.split('.')[1], VFlip['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_VFlip.'+j.split('.')[1], VFlip['mask'])

#   transform = A.VerticalFlip(p=1.0, always_apply=True)
#   VHFlip = transform(image=HFlip['image'], mask=HFlip['mask'])
#   cv2.imwrite(i.split('.')[0]+'_VHFlip.'+i.split('.')[1], VHFlip['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_VHFlip.'+j.split('.')[1], VHFlip['mask'])

#   transform = A.Rotate(p=1.0, always_apply=True)
#   R = transform(image=img, mask=mask)
#   #l.append(R['image'])
#   cv2.imwrite(i.split('.')[0]+'_R.'+i.split('.')[1], R['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_R.'+j.split('.')[1], R['mask'])


#   transform = A.ShiftScaleRotate(p=1.0, always_apply=True)
#   SSR = transform(image=img, mask=mask)
#   cv2.imwrite(i.split('.')[0]+'_SSR.'+i.split('.')[1], SSR['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_SSR.'+j.split('.')[1], SSR['mask'])

#   transform = A.ShiftScaleRotate(p=1.0, always_apply=True)
#   VHFlipSSR = transform(image=VHFlip['image'], mask=VHFlip['mask'])
#   cv2.imwrite(i.split('.')[0]+'_VHFlipSSR.'+i.split('.')[1], VHFlipSSR['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_VHFlipSSR.'+j.split('.')[1], VHFlipSSR['mask'])

#   transform = A.SafeRotate(p=1.0, always_apply=True)
#   SR = transform(image=img, mask=mask)
#   cv2.imwrite(i.split('.')[0]+'_RSC.'+i.split('.')[1], SR['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_RSC.'+j.split('.')[1], SR['mask'])

#   transform = A.SafeRotate(p=1.0, always_apply=True)
#   VHFlipSR = transform(image=VHFlip['image'], mask=VHFlip['mask'])
#   cv2.imwrite(i.split('.')[0]+'_VHFlipSR.'+i.split('.')[1], VHFlipSR['image'][:,:,::-1])
#   cv2.imwrite(j.split('.')[0]+'_VHFlipSR.'+j.split('.')[1], VHFlipSR['mask'])



aug_images, aug_masks = sorted(glob.glob('/content/drive/MyDrive/pipe_data_set/small_p_data/*.jpg')), sorted(glob.glob('/content/drive/MyDrive/pipe_data_set/merge_pipedata_label/*.jpg'))
print(len(aug_images),len(aug_masks))





def load_dataset(images, masks):

    train_x, test_x, train_y, test_y = train_test_split(images, masks, test_size=0.25, random_state=360, shuffle=True)
    train_x, val_x, train_y, val_y = train_test_split(train_x, train_y, test_size=0.15, random_state=360, shuffle=True)

    return train_x, val_x, train_y, val_y, test_x, test_y

train_x, val_x, train_y, val_y, test_x, test_y = load_dataset(sorted(aug_images[0:3000]), sorted(aug_masks[0:3000]))
print(len(train_x), len(val_x), len(train_y), len(val_y), len(test_x), len(test_y))

train_X_y_paths = list(zip(train_x, train_y))
val_X_y_paths = list(zip(test_x, test_y))
test_X_y_paths = list(zip(val_x, val_y))

from google.colab.patches import cv2_imshow

#print(train_y[5])
cv2_imshow(cv2.imread(test_x[5]))

def get_data_generator(samples,batch_size):

  while True:

    for offset in range(0, len(samples), batch_size):
      batch_samples = samples[offset:offset+batch_size]
      X_train = []
      Y_train = []

      for batch_sample in batch_samples:

        X_image = cv2.imread(batch_sample[0])[:,:,::-1]
        X_image = X_image / 255.0
        # X_image = cv2.resize(X_image, (256, 256))
        X_image = X_image.astype(np.float32)

        Y_image = cv2.imread(batch_sample[1], 0)
        Y_image = Y_image*255
        # Y_image = Y_image / 255.0
        Y_image = np.where(Y_image>199, 0.0, 1.0)
        # Y_image = cv2.resize(Y_image, (256, 256), fx=0, fy=0, interpolation=cv2.INTER_NEAREST)
        Y_image = tf.one_hot(Y_image, 1, dtype = np.float32)

        X_train.append(X_image)
        Y_train.append(Y_image)


      yield np.array(X_train), np.array(Y_train)

BATCH_SIZE = 32
train_generator = get_data_generator(train_X_y_paths,batch_size=BATCH_SIZE)
val_generator = get_data_generator(val_X_y_paths,batch_size=BATCH_SIZE)
test_generator = get_data_generator(test_X_y_paths,batch_size=BATCH_SIZE)

x_train, y_train = next(train_generator)
x_val, y_val  = next(val_generator)
x_test, y_test  = next(test_generator)

print(x_train.shape,y_train.shape)
print(x_val.shape, y_val.shape)
print(x_test.shape, y_test.shape)

print(np.unique((y_train[5])))

"""## U-Net

"""

!pip install -q segmentation_models

# from keras.models import Model
# from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda
# from keras.optimizers import Adam
# from keras.layers import Activation, MaxPool2D, Concatenate
# from keras import backend as K
# from segmentation_models.losses import bce_jaccard_loss, dice_loss, JaccardLoss, DiceLoss, BinaryCELoss
# from segmentation_models.metrics import iou_score, f1_score, precision, recall
# from keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, CSVLogger, EarlyStopping

# Commented out IPython magic to ensure Python compatibility.
import cv2
from glob import glob
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
# %env SM_FRAMEWORK=tf.keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm.auto import tqdm
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split
from keras import backend as K
from segmentation_models.losses import bce_jaccard_loss, dice_loss, JaccardLoss, DiceLoss, BinaryCELoss
from segmentation_models.metrics import iou_score, f1_score, precision, recall
from keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, CSVLogger, EarlyStopping

from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda
from keras.optimizers import Adam
from keras.layers import Activation, MaxPool2D, Concatenate

def conv_block(input, num_filters):
    x = Conv2D(num_filters, 3, padding="same")(input)
    # x = BatchNormalization()(x)   #Not in the original network.
    x = Activation("relu")(x)

    x = Conv2D(num_filters, 3, padding="same")(x)
    # x = BatchNormalization()(x)  #Not in the original network
    x = Activation("relu")(x)

    return x

#Encoder block: Conv block followed by maxpooling


def encoder_block(input, num_filters):
    x = conv_block(input, num_filters)
    p = MaxPool2D((2, 2))(x)
    return x, p

#Decoder block
#skip features gets input from encoder for concatenation

def decoder_block(input, skip_features, num_filters):
    x = Conv2DTranspose(num_filters, (2, 2), strides=2, padding="same")(input)
    x = Concatenate()([x, skip_features])
    x = conv_block(x, num_filters)
    return x

#Build Unet using the blocks
def build_unet(input_shape, n_classes):
    inputs = Input(input_shape)

    s1, p1 = encoder_block(inputs, 8)
    s2, p2 = encoder_block(p1, 16)
    s3, p3 = encoder_block(p2, 32)
    se, pe3 = encoder_block(p3, 64)

    b1 = conv_block(pe3, 128) #Bridge

    de = decoder_block( b1, se, 64)
    d2 = decoder_block(de, s3, 32)
    d3 = decoder_block(d2, s2, 16)
    d4 = decoder_block(d3, s1, 8)

    if n_classes == 1:  #Binary
      activation = 'sigmoid'
    else:
      activation = 'softmax'

    outputs = Conv2D(n_classes, 1, padding="same", activation=activation)(d4)  #Change the activation based on n_classes
    print(activation)

    model = Model(inputs, outputs, name="U-Net")
    return model

input_shape = (240,320,3)
print(input_shape)

model = build_unet(input_shape,1)

model.summary()

# from keras import backend as K
# def f1_score(y_true, y_pred):
#     true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
#     predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
#     actual_positives = K.sum(K.round(K.clip(y_true, 0, 1)))

#     precision = true_positives / (predicted_positives + K.epsilon())
#     recall = true_positives / (actual_positives + K.epsilon())

#     f1 = 2 * (precision * recall) / (precision + recall + K.epsilon())

#     return f1

ls =  JaccardLoss()*0.5 + DiceLoss()*0.5 + BinaryCELoss()
metrics = [precision, recall, f1_score, iou_score]
lr = 1e-1
csv_path = "history.csv"

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=lr), loss=ls, metrics=metrics)

train_steps = len(train_x)//BATCH_SIZE
if len(train_x) % BATCH_SIZE != 0:
    train_steps += 1

val_steps = len(val_x)//BATCH_SIZE
if len(val_x) % BATCH_SIZE != 0:
    val_steps += 1

checkpoint_filepath = 'Seg_00{epoch}.weights.h5'
model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_loss',
    mode='min',
    verbose = 1,
    save_best_only=False
    )

callbacks = [
    model_checkpoint_callback,
    ReduceLROnPlateau(monitor="val_loss", patience=3, factor=0.05, verbose=1, min_lr=1e-5),
    CSVLogger(csv_path),
    # EarlyStopping(monitor="val_loss", patience=5)
]



epochs = 100
h = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=epochs,
    steps_per_epoch=train_steps,
    validation_steps=val_steps,
    callbacks=callbacks,
    batch_size=BATCH_SIZE,
)

model.save('/content/drive/MyDrive/colab Notebook/first_model_100.h5')

import pandas as pd

history = pd.read_csv('history.csv')

plt.plot(history['loss'], label='train loss')
plt.plot(history['val_loss'], label='val loss')
plt.legend()
plt.show()

plt.plot(history['f1-score'], label='train f1-score')
plt.plot(history['val_f1-score'], label='val f1-score')
plt.legend()
plt.show()

plt.plot(history['iou_score'], label='train iou_score')
plt.plot(history['val_iou_score'], label='val iou_score')
plt.legend()
plt.show()

plt.plot(history['lr'], label='LR')
plt.legend()
plt.show()





test_steps = len(test_x)//BATCH_SIZE
if len(test_x) % BATCH_SIZE != 0:
    test_steps += 1

print(test_steps)

model.evaluate(test_generator, batch_size=BATCH_SIZE, steps=test_steps, workers=-1, use_multiprocessing=True)

print(np.shape(test_x[7]))

test = next(test_generator)[0]
test.shape

import sys
import tensorflow as tf
from keras.models import load_model

from keras import backend as K
def f1_score(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    actual_positives = K.sum(K.round(K.clip(y_true, 0, 1)))

    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (actual_positives + K.epsilon())

    f1 = 2 * (precision * recall) / (precision + recall + K.epsilon())

    return f1

model = load_model(r'first_model.h5', custom_objects={'f1_score': f1_score})

pred = model.predict(test)
pred.shape

import os
dir = r"/content/drive/MyDrive/bolt_U-Net_results/"
os.chdir(dir)



img_zero = np.zeros((240,320,3))
for i in range(len(pred)):
  cv2.resize(test[i], (320,240))
  io = cv2.resize(test[i], (320,240))
  img = cv2.resize(pred[i], (320,240))
  io = io*255
  img = img*255
  #img = pred[i]*255
  #img_zero[:,:,0] = img*255
  print(img_zero.shape, io.shape)
  #img_results = cv2.hconcat([img_zero,img_zero])
  #cv2_imshow(io)
  #cv2_imshow(img)
  cv2.imwrite(r"/content/drive/MyDrive/bolt_U-Net_results/img_input"+str(i)+".jpg",io)
  cv2.imwrite(r"/content/drive/MyDrive/bolt_U-Net_results/img_output"+str(i)+".jpg",img)

plt.imshow(test[47])
plt.show()
plt.imshow(pred[47], cmap='gray')

plt.show()

img = cv2.imread(images[350])[:,:,::-1]/255.0
plt.imshow(img)
plt.show()

mask = cv2.imread(masks[350], 0)
plt.imshow(mask, cmap='gray')
plt.show()

pred = m.predict(img.reshape(1, 240, 320, 3))
print(np.unique(pred))
pred = np.where(pred>=0.5, 0.0, 1.0)
print(np.unique(pred))
# pred = cv2.bitwise_not(pred)
# pred = np.where(pred==-2, 0.0, 1.0)
plt.imshow(pred.reshape(240, 320), cmap='gray')
plt.show()